package org.github.clbuttic.sodium4j;

/**
 * Constants for use for normal operations.
 *
 * ALL OF THESE MUST BE CHECKED ON EVERY LIBSODIUM RELEASE.
 */
public class Constants {
    /**
     * Private constructor, since we don't ever want this instantiated.
     */
    private Constants() {}

    /**
     * Base64 encoding using + / with padding.
     */
    public static final int SODIUM_BASE64_VARIANT_ORIGINAL = 1;

    /**
     * Base64 encoding using + / without padding.
     */
    public static final int SODIUM_BASE64_VARIANT_ORIGINAL_NO_PADDING = 3;

    /**
     * Base64 encoding using - _ with padding.
     */
    public static final int SODIUM_BASE64_VARIANT_URLSAFE = 5;

    /**
     * Base64 encoding using - _ without padding.
     */
    public static final int SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING = 7;

    /**
     * The length of a seed buffer.
     *
     * randombytes_SEEDBYTES
     */
    public static final int SODIUM_RANDOM_SEEDBYTES = 32;

    /**
     * The length of a public key used in a key exchange.
     *
     * crypto_kx_PUBLICKEYBYTES
     */
    public static final int SODIUM_KEY_EXCHANGE_PUBLIC_KEY = 32;

    /**
     * The length of a secret key used in a key exchange.
     *
     * crypto_kx_SECRETKEYBYTES
     */
    public static final int SODIUM_KEY_EXCHANGE_SECRET_KEY = 32;

    /**
     * The length of the session key generated by a key exchange.
     *
     * crypto_kx_SESSIONKEYBYTES
     */
    public static final int SODIUM_KEY_EXCHANGE_SESSION_KEY = 32;

}
